#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/Project-Fluid/manifest.git -b fluid-12.1 -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# local manifest
rm -rf prebuilts/gcc/linux-x86/aarch64 
git clone --depth=1 https://github.com/rubik-hub/android_device_oneplus_guacamoleb.git -b fluid-12.1 device/oneplus/guacamoleb
git clone --depth=1 https://github.com/w1zzyl/device_oneplus_sm8150-common.git -b fluid-12.1 device/oneplus/sm8150-common
git clone --depth=1 https://github.com/PixelOS-Devices/kernel_oneplus_sm8150.git kernel/oneplus/sm8150
git clone --depth=1 https://gitlab.com/rubik-hub/android_vendor_oneplus.git vendor/oneplus
git clone --depth=1 https://github.com/LineageOS/android_hardware_oneplus -b lineage-19.1 hardware/oneplus
git clone --depth=1 https://github.com/cyberknight777/gcc-arm64.git prebuilts/gcc/linux-x86/aarch64 

tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
